
name: update-user-blog-links

#display username of the person that uses the workflow
run-name: ${{user-name}} is updating profile  

# Controls when the workflow will run
on:
  # Triggers the workflow on push or commit events but only for the "main or master" branch
  push:
    branches: [ "main" ]
  create: 
    branches: ["main"]

jobs:
  # workflow contains a single job called "updating"
  build:
    # the job will run on 
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out my repository in my workspace
      - uses: actions/checkout@v3
      
      - name: blog-link
        run: Please type your blog-link
        
